const NODES = [
  {"id": "def_convex-body", "type": "def", "label": "convex body", "weight": 4, "proof": ""},
  {"id": "thm_boundary-measure", "type": "thm", "label": "boundary measure", "weight": 9, "proof": ""},
  {"id": "thm_convex-body-space", "type": "thm", "label": "convex body space", "weight": 2, "proof": ""},
  {"id": "def_convex-curve", "type": "def", "label": "convex curve", "weight": 3, "proof": ""},
  {"id": "lem_convex-curve-cut", "type": "lem", "label": "convex curve cut", "weight": 8, "proof": ""},
  {"id": "rem_gauss-minkowski", "type": "rem", "label": "gauss minkowski", "weight": 1, "proof": ""},
  {"id": "thm_convex-body-linear", "type": "thm", "label": "convex body linear", "weight": 9, "proof": ""},
  {"id": "lem_arm-length-convolution", "type": "lem", "label": "arm length convolution", "weight": 3, "proof": ""},
  {"id": "lem_convex-curve-bilinear-computation", "type": "lem", "label": "convex curve bilinear computation", "weight": 3, "proof": ""},
  {"id": "thm_convex-curve-area-functional", "type": "thm", "label": "convex curve area functional", "weight": 9, "proof": ""},
  {"id": "lem_convex-curve-jordan-curve", "type": "lem", "label": "convex curve jordan curve", "weight": 4, "proof": ""},
  {"id": "pro_cap-tail-space", "type": "pro", "label": "cap tail space", "weight": 2, "proof": ""},
  {"id": "thm_mamikon-convex", "type": "thm", "label": "mamikon convex", "weight": 3, "proof": ""},
  {"id": "thm_area-quadratic-expression", "type": "thm", "label": "area quadratic expression", "weight": 2, "proof": ""},
  {"id": "thm_tangent-line-param-linear", "type": "thm", "label": "tangent line param linear", "weight": 2, "proof": ""},
  {"id": "lem_leg-convergence", "type": "lem", "label": "leg convergence", "weight": 4, "proof": ""},
  {"id": "thm_arm-length-differentiation", "type": "thm", "label": "arm length differentiation", "weight": 3, "proof": ""},
  {"id": "thm_mamikon", "type": "thm", "label": "mamikon", "weight": 7, "proof": ""},
  {"id": "thm_convex-curve-area-variation", "type": "thm", "label": "convex curve area variation", "weight": 6, "proof": ""},
  {"id": "pro_upper-bound-q-quadratic", "type": "pro", "label": "upper bound q quadratic", "weight": 4, "proof": ""},
  {"id": "lem_upper-boundary-tracing", "type": "lem", "label": "upper boundary tracing", "weight": 5, "proof": ""},
  {"id": "lem_cap-left-right-tail", "type": "lem", "label": "cap left right tail", "weight": 6, "proof": ""},
  {"id": "lem_mamikon-sofa-convex", "type": "lem", "label": "mamikon sofa convex", "weight": 3, "proof": ""},
  {"id": "thm_balanced-ineq-limit", "type": "thm", "label": "balanced ineq limit", "weight": 4, "proof": ""},
  {"id": "thm_leg-length-bounds", "type": "thm", "label": "leg length bounds", "weight": 4, "proof": ""},
  {"id": "thm_variation-a2", "type": "thm", "label": "variation a2", "weight": 6, "proof": ""},
  {"id": "lem_mamikon-middle-eq", "type": "lem", "label": "mamikon middle eq", "weight": 5, "proof": ""},
  {"id": "thm_upper-bound-q", "type": "thm", "label": "upper bound q", "weight": 4, "proof": ""},
  {"id": "def_topological-operations", "type": "def", "label": "topological operations", "weight": 0, "proof": ""},
  {"id": "def_frame", "type": "def", "label": "frame", "weight": 0, "proof": ""},
  {"id": "def_line", "type": "def", "label": "line", "weight": 4, "proof": ""},
  {"id": "def_cap", "type": "def", "label": "cap", "weight": 21, "proof": ""},
  {"id": "pro_cap-trans-space", "type": "pro", "label": "cap trans space", "weight": 5, "proof": ""},
  {"id": "pro_jordan-curve-orientation", "type": "pro", "label": "jordan curve orientation", "weight": 6, "proof": ""},
  {"id": "def_angled-cap-space", "type": "def", "label": "angled cap space", "weight": 3, "proof": ""},
  {"id": "def_polyline-length", "type": "def", "label": "polyline length", "weight": 2, "proof": ""},
  {"id": "def_upper-half-planes", "type": "def", "label": "upper half planes", "weight": 2, "proof": ""},
  {"id": "def_cap-translate-extensions", "type": "def", "label": "cap translate extensions", "weight": 4, "proof": ""},
  {"id": "thm_gerver-monotone", "type": "thm", "label": "gerver monotone", "weight": 11, "proof": ""},
  {"id": "lem_wedge-gap-limit", "type": "lem", "label": "wedge gap limit", "weight": 3, "proof": ""},
  {"id": "pro_upper-boundary-connected", "type": "pro", "label": "upper boundary connected", "weight": 4, "proof": ""},
  {"id": "pro_mirror-reflection", "type": "pro", "label": "mirror reflection", "weight": 5, "proof": ""},
  {"id": "thm_cap-hallway-intersection", "type": "thm", "label": "cap hallway intersection", "weight": 5, "proof": ""},
  {"id": "thm_monotonization-structure", "type": "thm", "label": "monotonization structure", "weight": 4, "proof": ""},
  {"id": "def_wedge-side-lengths", "type": "def", "label": "wedge side lengths", "weight": 3, "proof": ""},
  {"id": "def_mirror-reflection", "type": "def", "label": "mirror reflection", "weight": 4, "proof": ""},
  {"id": "def_cap-space", "type": "def", "label": "cap space", "weight": 2, "proof": ""},
  {"id": "def_angled-niche", "type": "def", "label": "angled niche", "weight": 5, "proof": ""},
  {"id": "def_wedge-gap-infimum", "type": "def", "label": "wedge gap infimum", "weight": 1, "proof": ""},
  {"id": "def_injectivity-condition", "type": "def", "label": "injectivity condition", "weight": 6, "proof": ""},
  {"id": "def_right-left-body", "type": "def", "label": "right left body", "weight": 3, "proof": ""},
  {"id": "def_i-cap", "type": "def", "label": "i cap", "weight": 3, "proof": ""},
  {"id": "thm_variation-convex-body", "type": "thm", "label": "variation convex body", "weight": 4, "proof": ""},
  {"id": "pro_height-space-embedding", "type": "pro", "label": "height space embedding", "weight": 2, "proof": ""},
  {"id": "pro_cap-extension-compatible", "type": "pro", "label": "cap extension compatible", "weight": 6, "proof": ""},
  {"id": "pro_angled-cap", "type": "pro", "label": "angled cap", "weight": 9, "proof": ""},
  {"id": "pro_cap-translate-reduction", "type": "pro", "label": "cap translate reduction", "weight": 3, "proof": ""},
  {"id": "thm_height-extensions", "type": "thm", "label": "height extensions", "weight": 3, "proof": ""},
  {"id": "thm_gerver-left-right", "type": "thm", "label": "gerver left right", "weight": 6, "proof": ""},
  {"id": "rem_gerver-monotone", "type": "rem", "label": "gerver monotone", "weight": 2, "proof": ""},
  {"id": "thm_balanced-polygon-sofa-ineq", "type": "thm", "label": "balanced polygon sofa ineq", "weight": 4, "proof": ""},
  {"id": "thm_monotonization-connected-iff", "type": "thm", "label": "monotonization connected iff", "weight": 8, "proof": ""},
  {"id": "rem_mirror-symmetry", "type": "rem", "label": "mirror symmetry", "weight": 3, "proof": ""},
  {"id": "pro_cap-tangent-arm-mirror", "type": "pro", "label": "cap tangent arm mirror", "weight": 2, "proof": ""},
  {"id": "def_cap-real-definition", "type": "def", "label": "cap real definition", "weight": 1, "proof": ""},
  {"id": "thm_monotone-sofa-structure", "type": "thm", "label": "monotone sofa structure", "weight": 2, "proof": ""},
  {"id": "lem_maximum-polygon-cap-mirror", "type": "lem", "label": "maximum polygon cap mirror", "weight": 6, "proof": ""},
  {"id": "def_sofa-area-functional", "type": "def", "label": "sofa area functional", "weight": 6, "proof": ""},
  {"id": "pro_angled-niche-polygon-cap", "type": "pro", "label": "angled niche polygon cap", "weight": 3, "proof": ""},
  {"id": "thm_balanced-polygon-sofa-connected", "type": "thm", "label": "balanced polygon sofa connected", "weight": 4, "proof": ""},
  {"id": "pro_cap-nondegenerate", "type": "pro", "label": "cap nondegenerate", "weight": 3, "proof": ""},
  {"id": "cor_cap-nondegenerate", "type": "cor", "label": "cap nondegenerate", "weight": 4, "proof": ""},
  {"id": "def_cap-space-special", "type": "def", "label": "cap space special", "weight": 1, "proof": ""},
  {"id": "lem_monotonicity-intervals", "type": "lem", "label": "monotonicity intervals", "weight": 3, "proof": ""},
  {"id": "lem_right-left-body", "type": "lem", "label": "right left body", "weight": 7, "proof": ""},
  {"id": "thm_upper-bound-q-gerver", "type": "thm", "label": "upper bound q gerver", "weight": 4, "proof": ""},
  {"id": "thm_variation-inner-corner", "type": "thm", "label": "variation inner corner", "weight": 3, "proof": ""},
  {"id": "lem_height-positive-increment", "type": "lem", "label": "height positive increment", "weight": 5, "proof": ""},
  {"id": "pro_niche-extension-compatible", "type": "pro", "label": "niche extension compatible", "weight": 4, "proof": ""},
  {"id": "thm_polyline", "type": "thm", "label": "polyline", "weight": 6, "proof": ""},
  {"id": "def_simple-notation-balanced-cap", "type": "def", "label": "simple notation balanced cap", "weight": 4, "proof": ""},
  {"id": "thm_polygon-upper-bound", "type": "thm", "label": "polygon upper bound", "weight": 3, "proof": ""},
  {"id": "def_cap-trans", "type": "def", "label": "cap trans", "weight": 2, "proof": ""},
  {"id": "def_maximum-polygon-cap", "type": "def", "label": "maximum polygon cap", "weight": 6, "proof": ""},
  {"id": "def_polygon-cap-balanced", "type": "def", "label": "polygon cap balanced", "weight": 4, "proof": ""},
  {"id": "thm_balanced-polygon-sofa", "type": "thm", "label": "balanced polygon sofa", "weight": 7, "proof": ""},
  {"id": "pro_measure-translation", "type": "pro", "label": "measure translation", "weight": 2, "proof": ""},
  {"id": "thm_upper-bound-q-gerver-match", "type": "thm", "label": "upper bound q gerver match", "weight": 3, "proof": ""},
  {"id": "thm_balanced-maximum-sofa-ineq", "type": "thm", "label": "balanced maximum sofa ineq", "weight": 4, "proof": ""},
  {"id": "lem_leg-bounded", "type": "lem", "label": "leg bounded", "weight": 6, "proof": ""},
  {"id": "thm_niche-in-cap", "type": "thm", "label": "niche in cap", "weight": 5, "proof": ""},
  {"id": "thm_wedge-ends-in-cap", "type": "thm", "label": "wedge ends in cap", "weight": 6, "proof": ""},
  {"id": "thm_monotonization-idempotent", "type": "thm", "label": "monotonization idempotent", "weight": 2, "proof": ""},
  {"id": "thm_maximum-polygon-cap", "type": "thm", "label": "maximum polygon cap", "weight": 4, "proof": ""},
  {"id": "pro_balanced-maximum-cap-mirror", "type": "pro", "label": "balanced maximum cap mirror", "weight": 3, "proof": ""},
  {"id": "def_cap-space-right-angle", "type": "def", "label": "cap space right angle", "weight": 3, "proof": ""},
  {"id": "def_polygon-upper-bound", "type": "def", "label": "polygon upper bound", "weight": 3, "proof": ""},
  {"id": "def_height-extensions", "type": "def", "label": "height extensions", "weight": 3, "proof": ""},
  {"id": "rem_curve-area-functional-segment", "type": "rem", "label": "curve area functional segment", "weight": 2, "proof": ""},
  {"id": "rem_cap-tail-extension", "type": "rem", "label": "cap tail extension", "weight": 4, "proof": ""},
  {"id": "thm_limiting-maximum-cap-connected", "type": "thm", "label": "limiting maximum cap connected", "weight": 5, "proof": ""},
  {"id": "def_cap-nondegenerate", "type": "def", "label": "cap nondegenerate", "weight": 2, "proof": ""},
  {"id": "lem_cap-middle-lower-estimate", "type": "lem", "label": "cap middle lower estimate", "weight": 3, "proof": ""},
  {"id": "thm_cap-tail-extension", "type": "thm", "label": "cap tail extension", "weight": 5, "proof": ""},
  {"id": "thm_variation-a2-gerver", "type": "thm", "label": "variation a2 gerver", "weight": 4, "proof": ""},
  {"id": "def_polyline-of-cap", "type": "def", "label": "polyline of cap", "weight": 1, "proof": ""},
  {"id": "lem_polyline-length", "type": "lem", "label": "polyline length", "weight": 2, "proof": ""},
  {"id": "lem_leg-computation", "type": "lem", "label": "leg computation", "weight": 4, "proof": ""},
  {"id": "thm_limiting-maximum-cap-max", "type": "thm", "label": "limiting maximum cap max", "weight": 3, "proof": ""},
  {"id": "def_balanced-maximum-cap", "type": "def", "label": "balanced maximum cap", "weight": 9, "proof": ""},
  {"id": "rem_maximum-polygon-cap", "type": "rem", "label": "maximum polygon cap", "weight": 2, "proof": ""},
  {"id": "lem_not-balanced-positive", "type": "lem", "label": "not balanced positive", "weight": 2, "proof": ""},
  {"id": "rem_height-positive-increment", "type": "rem", "label": "height positive increment", "weight": 1, "proof": ""},
  {"id": "lem_balancing", "type": "lem", "label": "balancing", "weight": 5, "proof": ""},
  {"id": "def_half-plane", "type": "def", "label": "half plane", "weight": 5, "proof": ""},
  {"id": "def_line-half-plane-directions", "type": "def", "label": "line half plane directions", "weight": 1, "proof": ""},
  {"id": "def_nef-polygon", "type": "def", "label": "nef polygon", "weight": 3, "proof": ""},
  {"id": "def_simple-nef-polygon", "type": "def", "label": "simple nef polygon", "weight": 4, "proof": ""},
  {"id": "pro_cap-niche-nef-polygons", "type": "pro", "label": "cap niche nef polygons", "weight": 5, "proof": ""},
  {"id": "thm_simple-nef-polygon", "type": "thm", "label": "simple nef polygon", "weight": 2, "proof": ""},
  {"id": "def_support-function", "type": "def", "label": "support function", "weight": 6, "proof": ""},
  {"id": "pro_rotating-hallway-parts", "type": "pro", "label": "rotating hallway parts", "weight": 6, "proof": ""},
  {"id": "pro_tangent-hallway-contains", "type": "pro", "label": "tangent hallway contains", "weight": 2, "proof": ""},
  {"id": "pro_monotonization-contains-sofa", "type": "pro", "label": "monotonization contains sofa", "weight": 3, "proof": ""},
  {"id": "pro_cap-contains-sofa", "type": "pro", "label": "cap contains sofa", "weight": 3, "proof": ""},
  {"id": "lem_cap-same-support-function", "type": "lem", "label": "cap same support function", "weight": 4, "proof": ""},
  {"id": "thm_monotonization-is-connected", "type": "thm", "label": "monotonization is connected", "weight": 4, "proof": ""},
  {"id": "thm_monotonization", "type": "thm", "label": "monotonization", "weight": 1, "proof": ""},
  {"id": "thm_upper-bound-concave", "type": "thm", "label": "upper bound concave", "weight": 3, "proof": ""},
  {"id": "def_supporting-line-half-plane", "type": "def", "label": "supporting line half plane", "weight": 3, "proof": ""},
  {"id": "def_width", "type": "def", "label": "width", "weight": 3, "proof": ""},
  {"id": "def_convex-body-edge", "type": "def", "label": "convex body edge", "weight": 6, "proof": ""},
  {"id": "lem_polygon-cap-bounded", "type": "lem", "label": "polygon cap bounded", "weight": 4, "proof": ""},
  {"id": "def_convex-body-vertex", "type": "def", "label": "convex body vertex", "weight": 5, "proof": ""},
  {"id": "thm_surface-area-measure", "type": "thm", "label": "surface area measure", "weight": 3, "proof": ""},
  {"id": "def_right-triangle", "type": "def", "label": "right triangle", "weight": 11, "proof": ""},
  {"id": "lem_cap-wz-in-edge", "type": "lem", "label": "cap wz in edge", "weight": 4, "proof": ""},
  {"id": "def_strips", "type": "def", "label": "strips", "weight": 1, "proof": ""},
  {"id": "def_parallelogram", "type": "def", "label": "parallelogram", "weight": 5, "proof": ""},
  {"id": "pro_surface-area-measure-side-length", "type": "pro", "label": "surface area measure side length", "weight": 4, "proof": ""},
  {"id": "lem_cap-right-left-parallelogram", "type": "lem", "label": "cap right left parallelogram", "weight": 2, "proof": ""},
  {"id": "def_right-angle-set", "type": "def", "label": "right angle set", "weight": 3, "proof": ""},
  {"id": "pro_omega-gap", "type": "pro", "label": "omega gap", "weight": 3, "proof": ""},
  {"id": "def_gerver-constants", "type": "def", "label": "gerver constants", "weight": 1, "proof": ""},
  {"id": "rem_gerver-constants", "type": "rem", "label": "gerver constants", "weight": 1, "proof": ""},
  {"id": "thm_balanced-maximum-cap", "type": "thm", "label": "balanced maximum cap", "weight": 4, "proof": ""},
  {"id": "def_cap-right-left-parallelogram", "type": "def", "label": "cap right left parallelogram", "weight": 2, "proof": ""},
  {"id": "thm_balanced-consumed", "type": "thm", "label": "balanced consumed", "weight": 8, "proof": ""},
  {"id": "thm_limiting-maximum-sofa", "type": "thm", "label": "limiting maximum sofa", "weight": 5, "proof": ""},
  {"id": "lem_cap-left-right-disjoint", "type": "lem", "label": "cap left right disjoint", "weight": 1, "proof": ""},
  {"id": "pro_cap-nondegenerate-continuity", "type": "pro", "label": "cap nondegenerate continuity", "weight": 3, "proof": ""},
  {"id": "thm_balanced-discrete-ineq", "type": "thm", "label": "balanced discrete ineq", "weight": 3, "proof": ""},
  {"id": "lem_arm-length-discrete-bound", "type": "lem", "label": "arm length discrete bound", "weight": 2, "proof": ""},
  {"id": "cor_gerver-max-cap", "type": "cor", "label": "gerver max cap", "weight": 7, "proof": ""},
  {"id": "rem_quadratic-upper-bound", "type": "rem", "label": "quadratic upper bound", "weight": 2, "proof": ""},
  {"id": "def_hausdorff-measure", "type": "def", "label": "hausdorff measure", "weight": 0, "proof": ""},
  {"id": "def_hausdorff-distance", "type": "def", "label": "hausdorff distance", "weight": 4, "proof": ""},
  {"id": "lem_hausdorff-distance-containment", "type": "lem", "label": "hausdorff distance containment", "weight": 2, "proof": ""},
  {"id": "thm_surface-area-weak-convergence", "type": "thm", "label": "surface area weak convergence", "weight": 4, "proof": ""},
  {"id": "def_balanced-maximum-sofa", "type": "def", "label": "balanced maximum sofa", "weight": 4, "proof": ""},
  {"id": "def_surface-area-measure", "type": "def", "label": "surface area measure", "weight": 1, "proof": ""},
  {"id": "thm_injectivity", "type": "thm", "label": "injectivity", "weight": 3, "proof": ""},
  {"id": "def_convex-body-tangent-lines-intersection", "type": "def", "label": "convex body tangent lines intersection", "weight": 0, "proof": ""},
  {"id": "thm_limits-converging-to-vertex", "type": "thm", "label": "limits converging to vertex", "weight": 6, "proof": ""},
  {"id": "thm_inner-corner-deriv", "type": "thm", "label": "inner corner deriv", "weight": 3, "proof": ""},
  {"id": "thm_tangent-line-parametrization", "type": "thm", "label": "tangent line parametrization", "weight": 2, "proof": ""},
  {"id": "rem_inner-corner-deriv", "type": "rem", "label": "inner corner deriv", "weight": 2, "proof": ""},
  {"id": "rem_niche-not-in-cap", "type": "rem", "label": "niche not in cap", "weight": 1, "proof": ""},
  {"id": "thm_sofa-area-functional", "type": "thm", "label": "sofa area functional", "weight": 2, "proof": ""},
  {"id": "thm_injectivity-gerver", "type": "thm", "label": "injectivity gerver", "weight": 4, "proof": ""},
  {"id": "rem_injectivity-gerver", "type": "rem", "label": "injectivity gerver", "weight": 1, "proof": ""},
  {"id": "thm_cap-space-special", "type": "thm", "label": "cap space special", "weight": 3, "proof": ""},
  {"id": "def_hallway-parts", "type": "def", "label": "hallway parts", "weight": 2, "proof": ""},
  {"id": "pro_tangent-hallway", "type": "pro", "label": "tangent hallway", "weight": 3, "proof": ""},
  {"id": "def_tangent-hallway", "type": "def", "label": "tangent hallway", "weight": 3, "proof": ""},
  {"id": "lem_niche-in-cap", "type": "lem", "label": "niche in cap", "weight": 3, "proof": ""},
  {"id": "lem_cap-ends-not-in-niche", "type": "lem", "label": "cap ends not in niche", "weight": 2, "proof": ""},
  {"id": "def_rotating-hallway-parts", "type": "def", "label": "rotating hallway parts", "weight": 0, "proof": ""},
  {"id": "def_rotation-map", "type": "def", "label": "rotation map", "weight": 0, "proof": ""},
  {"id": "def_rotation-angle", "type": "def", "label": "rotation angle", "weight": 12, "proof": ""},
  {"id": "def_standard-position", "type": "def", "label": "standard position", "weight": 5, "proof": ""},
  {"id": "rem_angle-set", "type": "rem", "label": "angle set", "weight": 3, "proof": ""},
  {"id": "def_angle-domain", "type": "def", "label": "angle domain", "weight": 2, "proof": ""},
  {"id": "def_angled-cap", "type": "def", "label": "angled cap", "weight": 4, "proof": ""},
  {"id": "def_uniform-angle-set", "type": "def", "label": "uniform angle set", "weight": 3, "proof": ""},
  {"id": "pro_standard-position-shape", "type": "pro", "label": "standard position shape", "weight": 2, "proof": ""},
  {"id": "def_monotonization", "type": "def", "label": "monotonization", "weight": 2, "proof": ""},
  {"id": "def_cap-sofa", "type": "def", "label": "cap sofa", "weight": 3, "proof": ""},
  {"id": "def_monotone-sofa", "type": "def", "label": "monotone sofa", "weight": 4, "proof": ""},
  {"id": "def_closed-in-direction", "type": "def", "label": "closed in direction", "weight": 4, "proof": ""},
  {"id": "def_set-j", "type": "def", "label": "set j", "weight": 0, "proof": ""},
  {"id": "lem_lower-bound-sequence", "type": "lem", "label": "lower bound sequence", "weight": 2, "proof": ""},
  {"id": "thm_lower-bound-one", "type": "thm", "label": "lower bound one", "weight": 3, "proof": ""},
  {"id": "def_fan", "type": "def", "label": "fan", "weight": 0, "proof": ""},
  {"id": "def_niche", "type": "def", "label": "niche", "weight": 4, "proof": ""},
  {"id": "pro_wedge", "type": "pro", "label": "wedge", "weight": 2, "proof": ""},
  {"id": "def_cap-vertices", "type": "def", "label": "cap vertices", "weight": 0, "proof": ""},
  {"id": "def_upper-boundary-of-cap", "type": "def", "label": "upper boundary of cap", "weight": 1, "proof": ""},
  {"id": "pro_upper-boundary-interior", "type": "pro", "label": "upper boundary interior", "weight": 1, "proof": ""},
  {"id": "def_wedge", "type": "def", "label": "wedge", "weight": 2, "proof": ""},
  {"id": "def_wedge-endpoints", "type": "def", "label": "wedge endpoints", "weight": 0, "proof": ""},
  {"id": "def_further-in-direction", "type": "def", "label": "further in direction", "weight": 3, "proof": ""},
  {"id": "def_convex-space-directional-derivative", "type": "def", "label": "convex space directional derivative", "weight": 6, "proof": ""},
  {"id": "thm_variation-curve", "type": "thm", "label": "variation curve", "weight": 5, "proof": ""},
  {"id": "thm_variation-segment", "type": "thm", "label": "variation segment", "weight": 5, "proof": ""},
  {"id": "def_boolean-function", "type": "def", "label": "boolean function", "weight": 2, "proof": ""},
  {"id": "def_monotone-boolean-function", "type": "def", "label": "monotone boolean function", "weight": 5, "proof": ""},
  {"id": "pro_monotone-boolean-function", "type": "pro", "label": "monotone boolean function", "weight": 2, "proof": ""},
  {"id": "def_o-notation-subscript", "type": "def", "label": "o notation subscript", "weight": 12, "proof": ""},
  {"id": "rem_convex-spaces", "type": "rem", "label": "convex spaces", "weight": 2, "proof": ""},
  {"id": "thm_quadratic-variation", "type": "thm", "label": "quadratic variation", "weight": 4, "proof": ""},
  {"id": "def_modulo-linear", "type": "def", "label": "modulo linear", "weight": 3, "proof": ""},
  {"id": "def_angle-set", "type": "def", "label": "angle set", "weight": 9, "proof": ""},
  {"id": "rem_polygon-upper-bound", "type": "rem", "label": "polygon upper bound", "weight": 0, "proof": ""},
  {"id": "def_height-space", "type": "def", "label": "height space", "weight": 0, "proof": ""},
  {"id": "def_polyline", "type": "def", "label": "polyline", "weight": 0, "proof": ""},
  {"id": "def_d-min", "type": "def", "label": "d min", "weight": 1, "proof": ""},
  {"id": "def_cap-clipped", "type": "def", "label": "cap clipped", "weight": 1, "proof": ""},
  {"id": "lem_cap-support-elementary-bound", "type": "lem", "label": "cap support elementary bound", "weight": 1, "proof": ""},
  {"id": "lem_calculation-convex", "type": "lem", "label": "calculation convex", "weight": 1, "proof": ""},
  {"id": "lem_calculation-inequalities", "type": "lem", "label": "calculation inequalities", "weight": 2, "proof": ""},
  {"id": "def_calculation-variables", "type": "def", "label": "calculation variables", "weight": 1, "proof": ""},
  {"id": "def_function-measure-mult", "type": "def", "label": "function measure mult", "weight": 2, "proof": ""},
  {"id": "def_plane-cross-product", "type": "def", "label": "plane cross product", "weight": 1, "proof": ""},
  {"id": "def_bounded-variation", "type": "def", "label": "bounded variation", "weight": 6, "proof": ""},
  {"id": "def_lebesgue-stieltjes", "type": "def", "label": "lebesgue stieltjes", "weight": 4, "proof": ""},
  {"id": "pro_lebesgue-stieltjes-sum", "type": "pro", "label": "lebesgue stieltjes sum", "weight": 1, "proof": ""},
  {"id": "lem_integration-by-parts", "type": "lem", "label": "integration by parts", "weight": 4, "proof": ""},
  {"id": "lem_vertex-bounded-variation", "type": "lem", "label": "vertex bounded variation", "weight": 2, "proof": ""},
  {"id": "def_bounded-variation-space", "type": "def", "label": "bounded variation space", "weight": 1, "proof": ""},
  {"id": "def_mamikon", "type": "def", "label": "mamikon", "weight": 3, "proof": ""},
  {"id": "def_lebesgue-stieltjes-integral", "type": "def", "label": "lebesgue stieltjes integral", "weight": 1, "proof": ""},
  {"id": "pro_lebesgue-stieltjes-abs-cont", "type": "pro", "label": "lebesgue stieltjes abs cont", "weight": 3, "proof": ""},
  {"id": "lem_lebesgue-stieltjes-product", "type": "lem", "label": "lebesgue stieltjes product", "weight": 4, "proof": ""},
  {"id": "def_cap-tangent-arm-length", "type": "def", "label": "cap tangent arm length", "weight": 2, "proof": ""},
  {"id": "pro_cap-tangent-arm-length", "type": "pro", "label": "cap tangent arm length", "weight": 1, "proof": ""},
  {"id": "def_left-right-derivative", "type": "def", "label": "left right derivative", "weight": 0, "proof": ""},
  {"id": "def_magic-function", "type": "def", "label": "magic function", "weight": 0, "proof": ""},
  {"id": "def_integral-operator", "type": "def", "label": "integral operator", "weight": 1, "proof": ""},
  {"id": "lem_operator-monotonicity", "type": "lem", "label": "operator monotonicity", "weight": 2, "proof": ""},
  {"id": "lem_lower-bound-threshold", "type": "lem", "label": "lower bound threshold", "weight": 3, "proof": ""},
  {"id": "def_lower-bound-sequence", "type": "def", "label": "lower bound sequence", "weight": 0, "proof": ""},
  {"id": "def_lower-bound-j", "type": "def", "label": "lower bound j", "weight": 0, "proof": ""},
  {"id": "lem_lower-bound-j-iter", "type": "lem", "label": "lower bound j iter", "weight": 1, "proof": ""},
  {"id": "def_convex-spaces", "type": "def", "label": "convex spaces", "weight": 4, "proof": ""},
  {"id": "def_convex-linear", "type": "def", "label": "convex linear", "weight": 4, "proof": ""},
  {"id": "def_convex-space-concavity", "type": "def", "label": "convex space concavity", "weight": 13, "proof": ""},
  {"id": "def_convex-bilinear", "type": "def", "label": "convex bilinear", "weight": 2, "proof": ""},
  {"id": "lem_modulo-linear-const", "type": "lem", "label": "modulo linear const", "weight": 3, "proof": ""},
  {"id": "def_cap-tail-space", "type": "def", "label": "cap tail space", "weight": 3, "proof": ""},
  {"id": "def_right-left-tails", "type": "def", "label": "right left tails", "weight": 2, "proof": ""},
  {"id": "def_mamikon-right-left", "type": "def", "label": "mamikon right left", "weight": 2, "proof": ""},
  {"id": "def_opposite-surface-area", "type": "def", "label": "opposite surface area", "weight": 1, "proof": ""},
  {"id": "def_convex-space-quadratic", "type": "def", "label": "convex space quadratic", "weight": 6, "proof": ""},
  {"id": "thm_jordan-curve", "type": "thm", "label": "jordan curve", "weight": 2, "proof": ""},
  {"id": "lem_upper-bound-decomposition", "type": "lem", "label": "upper bound decomposition", "weight": 4, "proof": ""},
  {"id": "lem_derivative-calculation", "type": "lem", "label": "derivative calculation", "weight": 6, "proof": ""},
  {"id": "def_jordan-curve", "type": "def", "label": "jordan curve", "weight": 4, "proof": ""},
  {"id": "def_jordan-arc-orientation", "type": "def", "label": "jordan arc orientation", "weight": 5, "proof": ""},
  {"id": "def_jordan-curve-orientation", "type": "def", "label": "jordan curve orientation", "weight": 5, "proof": ""},
  {"id": "def_curve-area-jordan-arc", "type": "def", "label": "curve area jordan arc", "weight": 1, "proof": ""},
  {"id": "def_concatenation", "type": "def", "label": "concatenation", "weight": 5, "proof": ""},
  {"id": "thm_curve-area-functional-area", "type": "thm", "label": "curve area functional area", "weight": 4, "proof": ""},
  {"id": "lem_convex-curve-concat", "type": "lem", "label": "convex curve concat", "weight": 3, "proof": ""},
  {"id": "pro_curve-area-functional-additive", "type": "pro", "label": "curve area functional additive", "weight": 3, "proof": ""},
  {"id": "def_curve-area-functional", "type": "def", "label": "curve area functional", "weight": 5, "proof": ""},
  {"id": "pro_curve-area-line-segment", "type": "pro", "label": "curve area line segment", "weight": 3, "proof": ""},
  {"id": "pro_curve-area-line-segment-colinear", "type": "pro", "label": "curve area line segment colinear", "weight": 1, "proof": ""},
  {"id": "pro_curve-area-functional-quadratic", "type": "pro", "label": "curve area functional quadratic", "weight": 1, "proof": ""},
  {"id": "def_curve-area-line-segment", "type": "def", "label": "curve area line segment", "weight": 0, "proof": ""},
  {"id": "def_mamikon-region", "type": "def", "label": "mamikon region", "weight": 0, "proof": ""},
  {"id": "def_cap-left-right", "type": "def", "label": "cap left right", "weight": 0, "proof": ""},
  {"id": "def_upper-bound-q", "type": "def", "label": "upper bound q", "weight": 3, "proof": ""},
  {"id": "def_tangent-line-parametrization", "type": "def", "label": "tangent line parametrization", "weight": 0, "proof": ""},
  {"id": "def_mamikon-middle", "type": "def", "label": "mamikon middle", "weight": 1, "proof": ""},
  {"id": "def_upper-bound-middle", "type": "def", "label": "upper bound middle", "weight": 1, "proof": ""},
  {"id": "lem_linvals", "type": "lem", "label": "linvals", "weight": 1, "proof": ""},
  {"id": "def_gerver-intervals", "type": "def", "label": "gerver intervals", "weight": 1, "proof": ""},
  {"id": "def_interval-j", "type": "def", "label": "interval j", "weight": 2, "proof": ""},
  {"id": "def_gerver-x", "type": "def", "label": "gerver x", "weight": 1, "proof": ""},
  {"id": "def_gerver-abcd", "type": "def", "label": "gerver abcd", "weight": 1, "proof": ""},
  {"id": "def_bracket-dot-product", "type": "def", "label": "bracket dot product", "weight": 0, "proof": ""},
  {"id": "thm_gerver-odes", "type": "thm", "label": "gerver odes", "weight": 1, "proof": ""},
  {"id": "__legend__", "type": "", "label": "<<<<TABLE BORDER=\"0\" CELLBORDER=\"0\" CELLSPACING=\"2\">><<TR>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"10\">>corollary<</FONT>><</TD>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"9\">>ellipse<</FONT>><</TD>><<TD BGCOLOR=\"White\" BORDER=\"1\" COLOR=\"Blue\">><</TD>><</TR>><<TR>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"10\">>definition<</FONT>><</TD>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"9\">>ellipse<</FONT>><</TD>><<TD BGCOLOR=\"White\" BORDER=\"1\" COLOR=\"Blue\">><</TD>><</TR>><<TR>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"10\">>lemma<</FONT>><</TD>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"9\">>ellipse<</FONT>><</TD>><<TD BGCOLOR=\"White\" BORDER=\"1\" COLOR=\"Blue\">><</TD>><</TR>><<TR>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"10\">>proposition<</FONT>><</TD>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"9\">>ellipse<</FONT>><</TD>><<TD BGCOLOR=\"Lavender\" BORDER=\"1\" COLOR=\"SkyBlue\">><</TD>><</TR>><<TR>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"10\">>remark<</FONT>><</TD>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"9\">>ellipse<</FONT>><</TD>><<TD BGCOLOR=\"White\" BORDER=\"1\" COLOR=\"Blue\">><</TD>><</TR>><<TR>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"10\">>theorem<</FONT>><</TD>><<TD ALIGN=\"LEFT\">><<FONT POINT-SIZE=\"9\">>ellipse<</FONT>><</TD>><<TD BGCOLOR=\"White\" BORDER=\"1\" COLOR=\"Blue\">><</TD>><</TR>><<TR>><<TD COLSPAN=\"3\">><<FONT POINT-SIZE=\"6\">><</FONT>><</TD>><</TR>><<TR>><<TD ALIGN=\"LEFT\" COLSPAN=\"3\">><<FONT POINT-SIZE=\"9\">>\\&\\#8212;\\&\\#8212; solid = from proof<</FONT>><</TD>><</TR>><<TR>><<TD ALIGN=\"LEFT\" COLSPAN=\"3\">><<FONT POINT-SIZE=\"9\">>- - - dashed = from statement<</FONT>><</TD>><</TR>><<TR>><<TD ALIGN=\"LEFT\" COLSPAN=\"3\">><<FONT POINT-SIZE=\"9\">>\\&\\#183;\\&\\#183;\\&\\#183;\\&\\#183; dotted = heuristic<</FONT>><</TD>><</TR>><</TABLE>>>>", "weight": 0, "proof": ""},
];

const EDGES = [
  {"source": "def_convex-body", "target": "thm_boundary-measure", "type": "dashed"},
  {"source": "def_convex-body", "target": "thm_convex-body-space", "type": "dashed"},
  {"source": "def_convex-body", "target": "def_convex-curve", "type": "dashed"},
  {"source": "def_convex-body", "target": "lem_convex-curve-cut", "type": "dashed"},
  {"source": "thm_boundary-measure", "target": "rem_gauss-minkowski", "type": "dashed"},
  {"source": "thm_boundary-measure", "target": "thm_convex-body-linear", "type": "solid"},
  {"source": "thm_boundary-measure", "target": "lem_arm-length-convolution", "type": "solid"},
  {"source": "thm_boundary-measure", "target": "lem_convex-curve-bilinear-computation", "type": "solid"},
  {"source": "def_convex-curve", "target": "thm_convex-curve-area-functional", "type": "dashed"},
  {"source": "lem_convex-curve-cut", "target": "thm_convex-curve-area-functional", "type": "solid"},
  {"source": "lem_convex-curve-cut", "target": "lem_convex-curve-jordan-curve", "type": "solid"},
  {"source": "thm_convex-body-linear", "target": "pro_cap-tail-space", "type": "solid"},
  {"source": "thm_convex-body-linear", "target": "thm_mamikon-convex", "type": "solid"},
  {"source": "thm_convex-body-linear", "target": "thm_area-quadratic-expression", "type": "dashed"},
  {"source": "thm_convex-body-linear", "target": "thm_tangent-line-param-linear", "type": "solid"},
  {"source": "lem_arm-length-convolution", "target": "lem_leg-convergence", "type": "solid"},
  {"source": "lem_arm-length-convolution", "target": "thm_arm-length-differentiation", "type": "solid"},
  {"source": "lem_convex-curve-bilinear-computation", "target": "thm_mamikon", "type": "solid"},
  {"source": "lem_convex-curve-bilinear-computation", "target": "thm_convex-curve-area-variation", "type": "solid"},
  {"source": "thm_convex-curve-area-functional", "target": "pro_upper-bound-q-quadratic", "type": "solid"},
  {"source": "thm_convex-curve-area-functional", "target": "lem_upper-boundary-tracing", "type": "solid"},
  {"source": "lem_convex-curve-jordan-curve", "target": "thm_mamikon", "type": "solid"},
  {"source": "lem_convex-curve-jordan-curve", "target": "lem_cap-left-right-tail", "type": "solid"},
  {"source": "thm_mamikon-convex", "target": "lem_mamikon-sofa-convex", "type": "solid"},
  {"source": "thm_area-quadratic-expression", "target": "thm_convex-curve-area-functional", "type": "solid"},
  {"source": "thm_tangent-line-param-linear", "target": "lem_mamikon-sofa-convex", "type": "solid"},
  {"source": "lem_leg-convergence", "target": "thm_balanced-ineq-limit", "type": "solid"},
  {"source": "thm_arm-length-differentiation", "target": "thm_leg-length-bounds", "type": "solid"},
  {"source": "thm_mamikon", "target": "thm_mamikon-convex", "type": "solid"},
  {"source": "thm_convex-curve-area-variation", "target": "thm_variation-a2", "type": "solid"},
  {"source": "lem_upper-boundary-tracing", "target": "lem_mamikon-middle-eq", "type": "solid"},
  {"source": "lem_cap-left-right-tail", "target": "thm_upper-bound-q", "type": "solid"},
  {"source": "def_line", "target": "lem_convex-curve-cut", "type": "dashed"},
  {"source": "def_line", "target": "def_cap", "type": "dashed"},
  {"source": "def_line", "target": "pro_cap-trans-space", "type": "dashed"},
  {"source": "def_line", "target": "pro_jordan-curve-orientation", "type": "dashed"},
  {"source": "def_cap", "target": "def_angled-cap-space", "type": "dashed"},
  {"source": "def_cap", "target": "def_polyline-length", "type": "dashed"},
  {"source": "def_cap", "target": "def_upper-half-planes", "type": "dashed"},
  {"source": "def_cap", "target": "def_cap-translate-extensions", "type": "dashed"},
  {"source": "def_cap", "target": "thm_gerver-monotone", "type": "dashed"},
  {"source": "def_cap", "target": "lem_wedge-gap-limit", "type": "dashed"},
  {"source": "def_cap", "target": "pro_upper-boundary-connected", "type": "dashed"},
  {"source": "def_cap", "target": "pro_mirror-reflection", "type": "dashed"},
  {"source": "def_cap", "target": "thm_cap-hallway-intersection", "type": "solid"},
  {"source": "def_cap", "target": "thm_monotonization-structure", "type": "dashed"},
  {"source": "def_cap", "target": "def_wedge-side-lengths", "type": "dashed"},
  {"source": "def_cap", "target": "def_mirror-reflection", "type": "dashed"},
  {"source": "def_cap", "target": "def_cap-space", "type": "dashed"},
  {"source": "def_cap", "target": "def_angled-niche", "type": "dashed"},
  {"source": "def_cap", "target": "def_wedge-gap-infimum", "type": "dashed"},
  {"source": "def_cap", "target": "def_injectivity-condition", "type": "dashed"},
  {"source": "def_cap", "target": "def_right-left-body", "type": "dashed"},
  {"source": "def_cap", "target": "def_i-cap", "type": "dashed"},
  {"source": "def_cap", "target": "thm_variation-convex-body", "type": "dashed"},
  {"source": "pro_cap-trans-space", "target": "pro_height-space-embedding", "type": "solid"},
  {"source": "pro_cap-trans-space", "target": "pro_cap-extension-compatible", "type": "solid"},
  {"source": "pro_jordan-curve-orientation", "target": "lem_convex-curve-jordan-curve", "type": "solid"},
  {"source": "def_angled-cap-space", "target": "pro_angled-cap", "type": "dashed"},
  {"source": "def_cap-translate-extensions", "target": "pro_cap-translate-reduction", "type": "solid"},
  {"source": "def_cap-translate-extensions", "target": "thm_height-extensions", "type": "solid"},
  {"source": "thm_gerver-monotone", "target": "thm_gerver-left-right", "type": "solid"},
  {"source": "thm_gerver-monotone", "target": "rem_gerver-monotone", "type": "dashed"},
  {"source": "lem_wedge-gap-limit", "target": "thm_balanced-polygon-sofa-ineq", "type": "solid"},
  {"source": "pro_upper-boundary-connected", "target": "thm_monotonization-connected-iff", "type": "solid"},
  {"source": "pro_mirror-reflection", "target": "rem_mirror-symmetry", "type": "dashed"},
  {"source": "pro_mirror-reflection", "target": "pro_cap-tangent-arm-mirror", "type": "solid"},
  {"source": "thm_cap-hallway-intersection", "target": "def_cap-real-definition", "type": "dashed"},
  {"source": "thm_monotonization-structure", "target": "thm_monotone-sofa-structure", "type": "solid"},
  {"source": "def_mirror-reflection", "target": "rem_mirror-symmetry", "type": "dashed"},
  {"source": "def_mirror-reflection", "target": "lem_maximum-polygon-cap-mirror", "type": "dashed"},
  {"source": "def_cap-space", "target": "def_sofa-area-functional", "type": "dashed"},
  {"source": "def_angled-niche", "target": "pro_angled-niche-polygon-cap", "type": "solid"},
  {"source": "def_angled-niche", "target": "thm_balanced-polygon-sofa-connected", "type": "dashed"},
  {"source": "def_injectivity-condition", "target": "lem_upper-boundary-tracing", "type": "solid"},
  {"source": "def_injectivity-condition", "target": "pro_cap-nondegenerate", "type": "dashed"},
  {"source": "def_injectivity-condition", "target": "cor_cap-nondegenerate", "type": "dashed"},
  {"source": "def_injectivity-condition", "target": "def_cap-space-special", "type": "dashed"},
  {"source": "def_injectivity-condition", "target": "lem_monotonicity-intervals", "type": "solid"},
  {"source": "def_right-left-body", "target": "lem_right-left-body", "type": "solid"},
  {"source": "def_i-cap", "target": "thm_upper-bound-q-gerver", "type": "solid"},
  {"source": "def_i-cap", "target": "thm_variation-inner-corner", "type": "solid"},
  {"source": "thm_variation-convex-body", "target": "thm_variation-a2", "type": "solid"},
  {"source": "pro_cap-extension-compatible", "target": "pro_cap-translate-reduction", "type": "solid"},
  {"source": "pro_cap-extension-compatible", "target": "lem_height-positive-increment", "type": "dashed"},
  {"source": "pro_cap-extension-compatible", "target": "pro_niche-extension-compatible", "type": "solid"},
  {"source": "pro_angled-cap", "target": "lem_leg-convergence", "type": "solid"},
  {"source": "pro_angled-cap", "target": "thm_polyline", "type": "solid"},
  {"source": "pro_angled-cap", "target": "def_simple-notation-balanced-cap", "type": "solid"},
  {"source": "pro_angled-cap", "target": "thm_polygon-upper-bound", "type": "solid"},
  {"source": "pro_angled-cap", "target": "def_cap-trans", "type": "solid"},
  {"source": "pro_angled-cap", "target": "def_maximum-polygon-cap", "type": "solid"},
  {"source": "pro_angled-cap", "target": "def_polygon-cap-balanced", "type": "solid"},
  {"source": "pro_cap-translate-reduction", "target": "thm_balanced-polygon-sofa", "type": "solid"},
  {"source": "thm_gerver-left-right", "target": "pro_measure-translation", "type": "solid"},
  {"source": "thm_gerver-left-right", "target": "thm_upper-bound-q-gerver-match", "type": "solid"},
  {"source": "thm_balanced-polygon-sofa-ineq", "target": "thm_balanced-maximum-sofa-ineq", "type": "solid"},
  {"source": "thm_monotonization-connected-iff", "target": "lem_right-left-body", "type": "solid"},
  {"source": "thm_monotonization-connected-iff", "target": "lem_leg-bounded", "type": "solid"},
  {"source": "thm_monotonization-connected-iff", "target": "thm_niche-in-cap", "type": "solid"},
  {"source": "rem_mirror-symmetry", "target": "thm_wedge-ends-in-cap", "type": "solid"},
  {"source": "thm_monotone-sofa-structure", "target": "thm_monotonization-idempotent", "type": "solid"},
  {"source": "lem_maximum-polygon-cap-mirror", "target": "thm_balanced-polygon-sofa-ineq", "type": "solid"},
  {"source": "lem_maximum-polygon-cap-mirror", "target": "thm_balanced-polygon-sofa-connected", "type": "solid"},
  {"source": "lem_maximum-polygon-cap-mirror", "target": "thm_maximum-polygon-cap", "type": "solid"},
  {"source": "lem_maximum-polygon-cap-mirror", "target": "pro_balanced-maximum-cap-mirror", "type": "solid"},
  {"source": "def_sofa-area-functional", "target": "def_cap-space-right-angle", "type": "dashed"},
  {"source": "def_sofa-area-functional", "target": "def_polygon-upper-bound", "type": "dashed"},
  {"source": "def_sofa-area-functional", "target": "def_height-extensions", "type": "dashed"},
  {"source": "def_sofa-area-functional", "target": "rem_curve-area-functional-segment", "type": "dashed"},
  {"source": "def_sofa-area-functional", "target": "rem_cap-tail-extension", "type": "dashed"},
  {"source": "pro_angled-niche-polygon-cap", "target": "thm_polygon-upper-bound", "type": "solid"},
  {"source": "thm_balanced-polygon-sofa-connected", "target": "thm_limiting-maximum-cap-connected", "type": "solid"},
  {"source": "pro_cap-nondegenerate", "target": "def_cap-nondegenerate", "type": "dashed"},
  {"source": "cor_cap-nondegenerate", "target": "thm_leg-length-bounds", "type": "solid"},
  {"source": "lem_monotonicity-intervals", "target": "lem_right-left-body", "type": "solid"},
  {"source": "lem_monotonicity-intervals", "target": "lem_cap-middle-lower-estimate", "type": "solid"},
  {"source": "lem_right-left-body", "target": "lem_cap-left-right-tail", "type": "solid"},
  {"source": "lem_right-left-body", "target": "thm_gerver-left-right", "type": "solid"},
  {"source": "lem_right-left-body", "target": "thm_cap-tail-extension", "type": "solid"},
  {"source": "thm_upper-bound-q-gerver", "target": "thm_variation-a2-gerver", "type": "solid"},
  {"source": "thm_variation-inner-corner", "target": "thm_variation-a2", "type": "solid"},
  {"source": "thm_variation-a2", "target": "thm_variation-a2-gerver", "type": "solid"},
  {"source": "thm_polyline", "target": "def_polyline-of-cap", "type": "dashed"},
  {"source": "thm_polyline", "target": "lem_polyline-length", "type": "solid"},
  {"source": "def_simple-notation-balanced-cap", "target": "lem_leg-bounded", "type": "solid"},
  {"source": "def_simple-notation-balanced-cap", "target": "lem_leg-computation", "type": "dashed"},
  {"source": "thm_polygon-upper-bound", "target": "thm_limiting-maximum-cap-max", "type": "solid"},
  {"source": "def_cap-trans", "target": "pro_cap-extension-compatible", "type": "dashed"},
  {"source": "def_maximum-polygon-cap", "target": "lem_maximum-polygon-cap-mirror", "type": "dashed"},
  {"source": "def_maximum-polygon-cap", "target": "thm_balanced-polygon-sofa", "type": "dashed"},
  {"source": "def_maximum-polygon-cap", "target": "lem_leg-computation", "type": "dashed"},
  {"source": "def_maximum-polygon-cap", "target": "def_balanced-maximum-cap", "type": "dashed"},
  {"source": "def_maximum-polygon-cap", "target": "rem_maximum-polygon-cap", "type": "dashed"},
  {"source": "def_polygon-cap-balanced", "target": "def_balanced-maximum-cap", "type": "dashed"},
  {"source": "def_polygon-cap-balanced", "target": "lem_not-balanced-positive", "type": "dashed"},
  {"source": "lem_height-positive-increment", "target": "thm_balanced-polygon-sofa", "type": "solid"},
  {"source": "lem_height-positive-increment", "target": "rem_height-positive-increment", "type": "dashed"},
  {"source": "pro_niche-extension-compatible", "target": "thm_height-extensions", "type": "solid"},
  {"source": "pro_niche-extension-compatible", "target": "thm_balanced-polygon-sofa", "type": "solid"},
  {"source": "lem_polyline-length", "target": "lem_balancing", "type": "solid"},
  {"source": "lem_balancing", "target": "thm_balanced-polygon-sofa", "type": "solid"},
  {"source": "def_half-plane", "target": "lem_convex-curve-cut", "type": "dashed"},
  {"source": "def_half-plane", "target": "def_cap", "type": "dashed"},
  {"source": "def_half-plane", "target": "pro_jordan-curve-orientation", "type": "dashed"},
  {"source": "def_half-plane", "target": "def_line-half-plane-directions", "type": "dashed"},
  {"source": "def_half-plane", "target": "def_nef-polygon", "type": "dashed"},
  {"source": "def_nef-polygon", "target": "def_simple-nef-polygon", "type": "dashed"},
  {"source": "def_simple-nef-polygon", "target": "pro_cap-niche-nef-polygons", "type": "solid"},
  {"source": "def_simple-nef-polygon", "target": "thm_simple-nef-polygon", "type": "dashed"},
  {"source": "pro_cap-niche-nef-polygons", "target": "thm_height-extensions", "type": "solid"},
  {"source": "pro_cap-niche-nef-polygons", "target": "lem_balancing", "type": "solid"},
  {"source": "thm_simple-nef-polygon", "target": "lem_balancing", "type": "solid"},
  {"source": "def_support-function", "target": "thm_convex-body-linear", "type": "dashed"},
  {"source": "def_support-function", "target": "def_cap-translate-extensions", "type": "dashed"},
  {"source": "def_support-function", "target": "pro_height-space-embedding", "type": "dashed"},
  {"source": "def_support-function", "target": "lem_height-positive-increment", "type": "dashed"},
  {"source": "def_support-function", "target": "lem_balancing", "type": "dashed"},
  {"source": "def_support-function", "target": "pro_rotating-hallway-parts", "type": "dashed"},
  {"source": "pro_rotating-hallway-parts", "target": "pro_upper-bound-q-quadratic", "type": "solid"},
  {"source": "pro_rotating-hallway-parts", "target": "pro_niche-extension-compatible", "type": "solid"},
  {"source": "pro_rotating-hallway-parts", "target": "pro_tangent-hallway-contains", "type": "solid"},
  {"source": "pro_tangent-hallway-contains", "target": "pro_monotonization-contains-sofa", "type": "solid"},
  {"source": "thm_balanced-polygon-sofa", "target": "thm_balanced-polygon-sofa-ineq", "type": "solid"},
  {"source": "thm_balanced-polygon-sofa", "target": "thm_balanced-polygon-sofa-connected", "type": "solid"},
  {"source": "pro_monotonization-contains-sofa", "target": "pro_cap-contains-sofa", "type": "solid"},
  {"source": "lem_cap-same-support-function", "target": "thm_monotonization-structure", "type": "solid"},
  {"source": "lem_cap-same-support-function", "target": "thm_monotonization-is-connected", "type": "solid"},
  {"source": "thm_monotonization-is-connected", "target": "thm_monotonization", "type": "solid"},
  {"source": "lem_mamikon-sofa-convex", "target": "thm_upper-bound-concave", "type": "solid"},
  {"source": "def_supporting-line-half-plane", "target": "pro_rotating-hallway-parts", "type": "dashed"},
  {"source": "def_supporting-line-half-plane", "target": "def_width", "type": "dashed"},
  {"source": "def_supporting-line-half-plane", "target": "def_convex-body-edge", "type": "dashed"},
  {"source": "def_width", "target": "pro_cap-trans-space", "type": "dashed"},
  {"source": "def_width", "target": "lem_polygon-cap-bounded", "type": "dashed"},
  {"source": "def_convex-body-edge", "target": "def_polyline-length", "type": "dashed"},
  {"source": "def_convex-body-edge", "target": "def_convex-body-vertex", "type": "dashed"},
  {"source": "def_convex-body-edge", "target": "thm_surface-area-measure", "type": "dashed"},
  {"source": "def_convex-body-edge", "target": "def_right-triangle", "type": "dashed"},
  {"source": "def_convex-body-edge", "target": "lem_cap-wz-in-edge", "type": "dashed"},
  {"source": "lem_polygon-cap-bounded", "target": "thm_maximum-polygon-cap", "type": "solid"},
  {"source": "def_convex-body-vertex", "target": "thm_convex-body-linear", "type": "dashed"},
  {"source": "def_convex-body-vertex", "target": "thm_gerver-monotone", "type": "dashed"},
  {"source": "def_convex-body-vertex", "target": "def_strips", "type": "dashed"},
  {"source": "def_convex-body-vertex", "target": "def_parallelogram", "type": "dashed"},
  {"source": "thm_surface-area-measure", "target": "thm_convex-curve-area-functional", "type": "solid"},
  {"source": "thm_surface-area-measure", "target": "pro_surface-area-measure-side-length", "type": "solid"},
  {"source": "def_right-triangle", "target": "lem_convex-curve-cut", "type": "dashed"},
  {"source": "def_right-triangle", "target": "pro_jordan-curve-orientation", "type": "dashed"},
  {"source": "def_right-triangle", "target": "def_upper-half-planes", "type": "dashed"},
  {"source": "def_right-triangle", "target": "def_simple-notation-balanced-cap", "type": "dashed"},
  {"source": "def_right-triangle", "target": "lem_cap-right-left-parallelogram", "type": "dashed"},
  {"source": "def_right-triangle", "target": "def_cap-space-right-angle", "type": "dashed"},
  {"source": "def_right-triangle", "target": "def_right-angle-set", "type": "dashed"},
  {"source": "def_right-triangle", "target": "pro_omega-gap", "type": "dashed"},
  {"source": "def_right-triangle", "target": "def_gerver-constants", "type": "dashed"},
  {"source": "def_right-triangle", "target": "rem_gerver-constants", "type": "dashed"},
  {"source": "lem_cap-wz-in-edge", "target": "lem_right-left-body", "type": "solid"},
  {"source": "thm_maximum-polygon-cap", "target": "thm_balanced-maximum-cap", "type": "solid"},
  {"source": "def_parallelogram", "target": "lem_cap-right-left-parallelogram", "type": "dashed"},
  {"source": "def_parallelogram", "target": "pro_omega-gap", "type": "dashed"},
  {"source": "def_parallelogram", "target": "def_cap-right-left-parallelogram", "type": "dashed"},
  {"source": "pro_surface-area-measure-side-length", "target": "lem_leg-convergence", "type": "solid"},
  {"source": "pro_surface-area-measure-side-length", "target": "lem_upper-boundary-tracing", "type": "solid"},
  {"source": "pro_surface-area-measure-side-length", "target": "pro_cap-nondegenerate", "type": "solid"},
  {"source": "pro_omega-gap", "target": "thm_balanced-consumed", "type": "solid"},
  {"source": "thm_balanced-maximum-cap", "target": "thm_balanced-consumed", "type": "dashed"},
  {"source": "thm_balanced-maximum-cap", "target": "thm_limiting-maximum-sofa", "type": "solid"},
  {"source": "def_cap-right-left-parallelogram", "target": "lem_cap-left-right-disjoint", "type": "solid"},
  {"source": "thm_balanced-ineq-limit", "target": "cor_cap-nondegenerate", "type": "solid"},
  {"source": "def_cap-nondegenerate", "target": "pro_cap-nondegenerate-continuity", "type": "dashed"},
  {"source": "lem_mamikon-middle-eq", "target": "thm_upper-bound-concave", "type": "solid"},
  {"source": "lem_leg-bounded", "target": "thm_balanced-discrete-ineq", "type": "solid"},
  {"source": "lem_leg-bounded", "target": "lem_arm-length-discrete-bound", "type": "solid"},
  {"source": "lem_leg-computation", "target": "thm_balanced-discrete-ineq", "type": "solid"},
  {"source": "thm_cap-tail-extension", "target": "cor_gerver-max-cap", "type": "solid"},
  {"source": "thm_cap-tail-extension", "target": "rem_cap-tail-extension", "type": "dashed"},
  {"source": "thm_cap-tail-extension", "target": "rem_quadratic-upper-bound", "type": "dashed"},
  {"source": "pro_measure-translation", "target": "thm_upper-bound-q-gerver", "type": "solid"},
  {"source": "thm_upper-bound-q-gerver-match", "target": "cor_gerver-max-cap", "type": "solid"},
  {"source": "def_hausdorff-distance", "target": "lem_wedge-gap-limit", "type": "dashed"},
  {"source": "def_hausdorff-distance", "target": "def_balanced-maximum-cap", "type": "dashed"},
  {"source": "def_hausdorff-distance", "target": "lem_hausdorff-distance-containment", "type": "dashed"},
  {"source": "def_hausdorff-distance", "target": "thm_surface-area-weak-convergence", "type": "dashed"},
  {"source": "def_balanced-maximum-cap", "target": "thm_balanced-maximum-cap", "type": "dashed"},
  {"source": "def_balanced-maximum-cap", "target": "thm_balanced-maximum-sofa-ineq", "type": "dashed"},
  {"source": "def_balanced-maximum-cap", "target": "def_balanced-maximum-sofa", "type": "dashed"},
  {"source": "def_balanced-maximum-cap", "target": "pro_balanced-maximum-cap-mirror", "type": "dashed"},
  {"source": "def_balanced-maximum-cap", "target": "thm_limiting-maximum-cap-connected", "type": "dashed"},
  {"source": "lem_hausdorff-distance-containment", "target": "thm_limiting-maximum-cap-connected", "type": "solid"},
  {"source": "thm_surface-area-weak-convergence", "target": "thm_boundary-measure", "type": "solid"},
  {"source": "thm_surface-area-weak-convergence", "target": "thm_balanced-maximum-sofa-ineq", "type": "solid"},
  {"source": "thm_balanced-maximum-sofa-ineq", "target": "thm_balanced-consumed", "type": "solid"},
  {"source": "def_balanced-maximum-sofa", "target": "thm_limiting-maximum-sofa", "type": "dashed"},
  {"source": "pro_balanced-maximum-cap-mirror", "target": "cor_cap-nondegenerate", "type": "solid"},
  {"source": "thm_limiting-maximum-cap-connected", "target": "lem_leg-bounded", "type": "solid"},
  {"source": "thm_limiting-maximum-cap-connected", "target": "thm_limiting-maximum-cap-max", "type": "solid"},
  {"source": "thm_limiting-maximum-sofa", "target": "cor_gerver-max-cap", "type": "solid"},
  {"source": "thm_limiting-maximum-cap-max", "target": "thm_limiting-maximum-sofa", "type": "solid"},
  {"source": "def_surface-area-measure", "target": "thm_surface-area-weak-convergence", "type": "dashed"},
  {"source": "pro_cap-nondegenerate-continuity", "target": "thm_injectivity", "type": "solid"},
  {"source": "thm_limits-converging-to-vertex", "target": "thm_convex-body-linear", "type": "solid"},
  {"source": "thm_limits-converging-to-vertex", "target": "thm_mamikon", "type": "solid"},
  {"source": "thm_limits-converging-to-vertex", "target": "thm_convex-curve-area-variation", "type": "solid"},
  {"source": "thm_limits-converging-to-vertex", "target": "pro_upper-boundary-connected", "type": "solid"},
  {"source": "thm_limits-converging-to-vertex", "target": "thm_inner-corner-deriv", "type": "solid"},
  {"source": "thm_limits-converging-to-vertex", "target": "thm_tangent-line-parametrization", "type": "solid"},
  {"source": "thm_inner-corner-deriv", "target": "pro_cap-nondegenerate-continuity", "type": "solid"},
  {"source": "thm_inner-corner-deriv", "target": "rem_inner-corner-deriv", "type": "dashed"},
  {"source": "thm_niche-in-cap", "target": "thm_gerver-left-right", "type": "solid"},
  {"source": "thm_niche-in-cap", "target": "rem_niche-not-in-cap", "type": "dashed"},
  {"source": "thm_niche-in-cap", "target": "thm_sofa-area-functional", "type": "solid"},
  {"source": "thm_injectivity", "target": "thm_injectivity-gerver", "type": "solid"},
  {"source": "thm_injectivity-gerver", "target": "thm_gerver-left-right", "type": "solid"},
  {"source": "thm_injectivity-gerver", "target": "rem_injectivity-gerver", "type": "dashed"},
  {"source": "thm_injectivity-gerver", "target": "thm_cap-space-special", "type": "solid"},
  {"source": "thm_variation-a2-gerver", "target": "cor_gerver-max-cap", "type": "solid"},
  {"source": "def_hallway-parts", "target": "thm_gerver-monotone", "type": "dashed"},
  {"source": "def_hallway-parts", "target": "pro_tangent-hallway", "type": "solid"},
  {"source": "pro_tangent-hallway", "target": "pro_rotating-hallway-parts", "type": "solid"},
  {"source": "def_tangent-hallway", "target": "thm_gerver-monotone", "type": "dashed"},
  {"source": "def_tangent-hallway", "target": "pro_mirror-reflection", "type": "dashed"},
  {"source": "def_tangent-hallway", "target": "pro_tangent-hallway", "type": "dashed"},
  {"source": "pro_cap-contains-sofa", "target": "thm_cap-hallway-intersection", "type": "solid"},
  {"source": "pro_cap-contains-sofa", "target": "lem_cap-same-support-function", "type": "solid"},
  {"source": "thm_wedge-ends-in-cap", "target": "thm_polyline", "type": "solid"},
  {"source": "thm_wedge-ends-in-cap", "target": "lem_cap-wz-in-edge", "type": "solid"},
  {"source": "thm_wedge-ends-in-cap", "target": "lem_niche-in-cap", "type": "solid"},
  {"source": "thm_wedge-ends-in-cap", "target": "lem_cap-ends-not-in-niche", "type": "solid"},
  {"source": "def_rotation-angle", "target": "def_wedge-side-lengths", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "def_mirror-reflection", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "lem_polygon-cap-bounded", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "def_parallelogram", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "def_cap-space-right-angle", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "def_right-angle-set", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "def_standard-position", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "rem_angle-set", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "def_angle-domain", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "def_angled-cap", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "def_polygon-upper-bound", "type": "dashed"},
  {"source": "def_rotation-angle", "target": "def_uniform-angle-set", "type": "dashed"},
  {"source": "def_standard-position", "target": "pro_standard-position-shape", "type": "dashed"},
  {"source": "def_standard-position", "target": "def_monotonization", "type": "dashed"},
  {"source": "def_standard-position", "target": "def_cap-sofa", "type": "dashed"},
  {"source": "def_standard-position", "target": "def_monotone-sofa", "type": "dashed"},
  {"source": "def_angled-cap", "target": "pro_angled-cap", "type": "solid"},
  {"source": "def_angled-cap", "target": "pro_angled-niche-polygon-cap", "type": "solid"},
  {"source": "def_uniform-angle-set", "target": "def_balanced-maximum-cap", "type": "dashed"},
  {"source": "pro_standard-position-shape", "target": "pro_monotonization-contains-sofa", "type": "solid"},
  {"source": "def_monotonization", "target": "thm_monotonization-is-connected", "type": "solid"},
  {"source": "def_cap-sofa", "target": "thm_cap-hallway-intersection", "type": "solid"},
  {"source": "def_cap-sofa", "target": "lem_cap-same-support-function", "type": "solid"},
  {"source": "def_monotone-sofa", "target": "thm_gerver-monotone", "type": "dashed"},
  {"source": "def_monotone-sofa", "target": "thm_monotonization-structure", "type": "dashed"},
  {"source": "def_monotone-sofa", "target": "def_balanced-maximum-sofa", "type": "dashed"},
  {"source": "thm_monotonization-idempotent", "target": "thm_niche-in-cap", "type": "solid"},
  {"source": "thm_sofa-area-functional", "target": "thm_limiting-maximum-sofa", "type": "solid"},
  {"source": "def_closed-in-direction", "target": "thm_cap-hallway-intersection", "type": "solid"},
  {"source": "def_closed-in-direction", "target": "thm_monotonization-connected-iff", "type": "solid"},
  {"source": "def_closed-in-direction", "target": "thm_polyline", "type": "solid"},
  {"source": "def_closed-in-direction", "target": "thm_monotonization-is-connected", "type": "solid"},
  {"source": "thm_balanced-discrete-ineq", "target": "thm_balanced-ineq-limit", "type": "solid"},
  {"source": "lem_arm-length-discrete-bound", "target": "thm_balanced-ineq-limit", "type": "solid"},
  {"source": "def_height-extensions", "target": "pro_cap-extension-compatible", "type": "solid"},
  {"source": "def_height-extensions", "target": "pro_cap-niche-nef-polygons", "type": "solid"},
  {"source": "lem_niche-in-cap", "target": "thm_monotonization-connected-iff", "type": "solid"},
  {"source": "lem_cap-ends-not-in-niche", "target": "thm_monotonization-connected-iff", "type": "solid"},
  {"source": "lem_not-balanced-positive", "target": "lem_height-positive-increment", "type": "solid"},
  {"source": "thm_leg-length-bounds", "target": "lem_lower-bound-sequence", "type": "solid"},
  {"source": "lem_cap-middle-lower-estimate", "target": "thm_upper-bound-q", "type": "solid"},
  {"source": "thm_cap-space-special", "target": "cor_gerver-max-cap", "type": "solid"},
  {"source": "lem_lower-bound-sequence", "target": "thm_lower-bound-one", "type": "solid"},
  {"source": "thm_lower-bound-one", "target": "thm_injectivity", "type": "solid"},
  {"source": "thm_upper-bound-q", "target": "cor_gerver-max-cap", "type": "solid"},
  {"source": "thm_upper-bound-q", "target": "rem_cap-tail-extension", "type": "dashed"},
  {"source": "def_niche", "target": "thm_gerver-monotone", "type": "dashed"},
  {"source": "def_niche", "target": "pro_mirror-reflection", "type": "dashed"},
  {"source": "def_niche", "target": "def_angled-niche", "type": "dashed"},
  {"source": "def_niche", "target": "pro_wedge", "type": "solid"},
  {"source": "pro_wedge", "target": "thm_maximum-polygon-cap", "type": "solid"},
  {"source": "def_upper-boundary-of-cap", "target": "pro_upper-boundary-connected", "type": "dashed"},
  {"source": "pro_upper-boundary-interior", "target": "thm_monotonization-connected-iff", "type": "solid"},
  {"source": "def_wedge", "target": "def_wedge-side-lengths", "type": "dashed"},
  {"source": "def_wedge", "target": "lem_niche-in-cap", "type": "dashed"},
  {"source": "def_further-in-direction", "target": "rem_inner-corner-deriv", "type": "dashed"},
  {"source": "def_further-in-direction", "target": "thm_wedge-ends-in-cap", "type": "solid"},
  {"source": "def_further-in-direction", "target": "def_convex-space-directional-derivative", "type": "dashed"},
  {"source": "def_convex-space-directional-derivative", "target": "thm_convex-curve-area-variation", "type": "dashed"},
  {"source": "def_convex-space-directional-derivative", "target": "thm_variation-convex-body", "type": "dashed"},
  {"source": "def_convex-space-directional-derivative", "target": "thm_variation-curve", "type": "dashed"},
  {"source": "def_convex-space-directional-derivative", "target": "thm_variation-segment", "type": "dashed"},
  {"source": "thm_variation-curve", "target": "thm_variation-inner-corner", "type": "solid"},
  {"source": "thm_variation-segment", "target": "thm_variation-a2", "type": "solid"},
  {"source": "def_boolean-function", "target": "def_nef-polygon", "type": "dashed"},
  {"source": "def_boolean-function", "target": "def_monotone-boolean-function", "type": "dashed"},
  {"source": "def_monotone-boolean-function", "target": "thm_gerver-monotone", "type": "dashed"},
  {"source": "def_monotone-boolean-function", "target": "def_simple-nef-polygon", "type": "dashed"},
  {"source": "def_monotone-boolean-function", "target": "def_balanced-maximum-sofa", "type": "dashed"},
  {"source": "def_monotone-boolean-function", "target": "pro_monotone-boolean-function", "type": "dashed"},
  {"source": "pro_monotone-boolean-function", "target": "pro_cap-niche-nef-polygons", "type": "solid"},
  {"source": "def_o-notation-subscript", "target": "lem_convex-curve-cut", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "pro_cap-trans-space", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "rem_gerver-monotone", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "thm_polyline", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "def_polygon-cap-balanced", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "rem_angle-set", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "rem_maximum-polygon-cap", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "rem_curve-area-functional-segment", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "rem_quadratic-upper-bound", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "rem_convex-spaces", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "thm_quadratic-variation", "type": "dashed"},
  {"source": "def_o-notation-subscript", "target": "def_modulo-linear", "type": "dashed"},
  {"source": "thm_quadratic-variation", "target": "cor_gerver-max-cap", "type": "solid"},
  {"source": "def_angle-set", "target": "def_angled-cap-space", "type": "dashed"},
  {"source": "def_angle-set", "target": "def_angled-niche", "type": "dashed"},
  {"source": "def_angle-set", "target": "lem_polygon-cap-bounded", "type": "dashed"},
  {"source": "def_angle-set", "target": "def_right-angle-set", "type": "dashed"},
  {"source": "def_angle-set", "target": "rem_angle-set", "type": "dashed"},
  {"source": "def_angle-set", "target": "def_angle-domain", "type": "dashed"},
  {"source": "def_angle-set", "target": "def_angled-cap", "type": "dashed"},
  {"source": "def_angle-set", "target": "def_polygon-upper-bound", "type": "dashed"},
  {"source": "def_angle-set", "target": "def_uniform-angle-set", "type": "dashed"},
  {"source": "def_d-min", "target": "thm_balanced-consumed", "type": "solid"},
  {"source": "def_cap-clipped", "target": "thm_balanced-consumed", "type": "solid"},
  {"source": "lem_cap-support-elementary-bound", "target": "thm_balanced-consumed", "type": "solid"},
  {"source": "lem_calculation-convex", "target": "lem_calculation-inequalities", "type": "solid"},
  {"source": "lem_calculation-inequalities", "target": "thm_balanced-consumed", "type": "solid"},
  {"source": "def_calculation-variables", "target": "thm_balanced-consumed", "type": "solid"},
  {"source": "def_function-measure-mult", "target": "thm_boundary-measure", "type": "dashed"},
  {"source": "def_function-measure-mult", "target": "def_plane-cross-product", "type": "dashed"},
  {"source": "def_bounded-variation", "target": "def_lebesgue-stieltjes", "type": "dashed"},
  {"source": "def_bounded-variation", "target": "pro_lebesgue-stieltjes-sum", "type": "dashed"},
  {"source": "def_bounded-variation", "target": "lem_integration-by-parts", "type": "dashed"},
  {"source": "def_bounded-variation", "target": "lem_vertex-bounded-variation", "type": "dashed"},
  {"source": "def_bounded-variation", "target": "def_bounded-variation-space", "type": "dashed"},
  {"source": "def_bounded-variation", "target": "def_mamikon", "type": "dashed"},
  {"source": "def_lebesgue-stieltjes", "target": "thm_boundary-measure", "type": "dashed"},
  {"source": "def_lebesgue-stieltjes", "target": "def_lebesgue-stieltjes-integral", "type": "dashed"},
  {"source": "def_lebesgue-stieltjes", "target": "pro_lebesgue-stieltjes-abs-cont", "type": "solid"},
  {"source": "lem_integration-by-parts", "target": "thm_convex-curve-area-variation", "type": "solid"},
  {"source": "lem_integration-by-parts", "target": "thm_variation-curve", "type": "solid"},
  {"source": "lem_integration-by-parts", "target": "lem_lebesgue-stieltjes-product", "type": "solid"},
  {"source": "lem_vertex-bounded-variation", "target": "thm_boundary-measure", "type": "solid"},
  {"source": "def_mamikon", "target": "thm_mamikon", "type": "solid"},
  {"source": "def_mamikon", "target": "lem_mamikon-middle-eq", "type": "solid"},
  {"source": "pro_lebesgue-stieltjes-abs-cont", "target": "thm_leg-length-bounds", "type": "solid"},
  {"source": "lem_lebesgue-stieltjes-product", "target": "thm_arm-length-differentiation", "type": "solid"},
  {"source": "lem_lebesgue-stieltjes-product", "target": "thm_mamikon", "type": "solid"},
  {"source": "lem_lebesgue-stieltjes-product", "target": "pro_lebesgue-stieltjes-abs-cont", "type": "solid"},
  {"source": "def_cap-tangent-arm-length", "target": "pro_cap-tangent-arm-mirror", "type": "solid"},
  {"source": "def_cap-tangent-arm-length", "target": "lem_leg-bounded", "type": "solid"},
  {"source": "pro_cap-tangent-arm-length", "target": "lem_leg-computation", "type": "solid"},
  {"source": "def_integral-operator", "target": "lem_operator-monotonicity", "type": "solid"},
  {"source": "lem_operator-monotonicity", "target": "lem_lower-bound-threshold", "type": "solid"},
  {"source": "lem_lower-bound-threshold", "target": "thm_lower-bound-one", "type": "solid"},
  {"source": "lem_lower-bound-j-iter", "target": "lem_lower-bound-threshold", "type": "solid"},
  {"source": "def_convex-spaces", "target": "thm_convex-body-space", "type": "dashed"},
  {"source": "def_convex-spaces", "target": "rem_convex-spaces", "type": "dashed"},
  {"source": "def_convex-spaces", "target": "def_convex-linear", "type": "dashed"},
  {"source": "def_convex-spaces", "target": "def_convex-space-concavity", "type": "dashed"},
  {"source": "def_convex-linear", "target": "thm_convex-body-linear", "type": "dashed"},
  {"source": "def_convex-linear", "target": "def_modulo-linear", "type": "dashed"},
  {"source": "def_convex-linear", "target": "def_convex-bilinear", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "def_convex-curve", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "lem_convex-curve-cut", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "def_right-left-body", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "thm_cap-space-special", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "thm_variation-segment", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "thm_quadratic-variation", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "def_modulo-linear", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "lem_modulo-linear-const", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "def_cap-tail-space", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "def_right-left-tails", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "def_mamikon-right-left", "type": "dashed"},
  {"source": "def_convex-space-concavity", "target": "def_opposite-surface-area", "type": "dashed"},
  {"source": "def_convex-bilinear", "target": "def_convex-space-quadratic", "type": "dashed"},
  {"source": "lem_modulo-linear-const", "target": "thm_jordan-curve", "type": "solid"},
  {"source": "def_cap-tail-space", "target": "pro_cap-tail-space", "type": "solid"},
  {"source": "def_cap-tail-space", "target": "thm_cap-tail-extension", "type": "solid"},
  {"source": "def_right-left-tails", "target": "lem_cap-left-right-tail", "type": "solid"},
  {"source": "def_mamikon-right-left", "target": "lem_upper-bound-decomposition", "type": "solid"},
  {"source": "def_convex-space-quadratic", "target": "pro_upper-bound-q-quadratic", "type": "dashed"},
  {"source": "def_convex-space-quadratic", "target": "rem_cap-tail-extension", "type": "dashed"},
  {"source": "def_convex-space-quadratic", "target": "def_convex-space-directional-derivative", "type": "dashed"},
  {"source": "def_convex-space-quadratic", "target": "lem_modulo-linear-const", "type": "dashed"},
  {"source": "def_convex-space-quadratic", "target": "lem_derivative-calculation", "type": "dashed"},
  {"source": "lem_derivative-calculation", "target": "thm_convex-curve-area-variation", "type": "solid"},
  {"source": "lem_derivative-calculation", "target": "thm_variation-convex-body", "type": "solid"},
  {"source": "lem_derivative-calculation", "target": "thm_variation-curve", "type": "solid"},
  {"source": "lem_derivative-calculation", "target": "thm_variation-segment", "type": "solid"},
  {"source": "lem_derivative-calculation", "target": "thm_quadratic-variation", "type": "solid"},
  {"source": "lem_upper-bound-decomposition", "target": "thm_upper-bound-concave", "type": "solid"},
  {"source": "def_jordan-curve", "target": "thm_tangent-line-parametrization", "type": "dashed"},
  {"source": "def_jordan-curve", "target": "thm_jordan-curve", "type": "dashed"},
  {"source": "def_jordan-curve", "target": "def_jordan-arc-orientation", "type": "dashed"},
  {"source": "def_jordan-curve", "target": "def_jordan-curve-orientation", "type": "dashed"},
  {"source": "def_jordan-arc-orientation", "target": "thm_convex-curve-area-functional", "type": "dashed"},
  {"source": "def_jordan-arc-orientation", "target": "lem_cap-wz-in-edge", "type": "dashed"},
  {"source": "def_jordan-arc-orientation", "target": "def_curve-area-jordan-arc", "type": "dashed"},
  {"source": "def_jordan-arc-orientation", "target": "def_concatenation", "type": "dashed"},
  {"source": "def_jordan-curve-orientation", "target": "pro_jordan-curve-orientation", "type": "dashed"},
  {"source": "def_jordan-curve-orientation", "target": "thm_gerver-monotone", "type": "dashed"},
  {"source": "def_jordan-curve-orientation", "target": "thm_curve-area-functional-area", "type": "dashed"},
  {"source": "def_jordan-curve-orientation", "target": "lem_convex-curve-concat", "type": "dashed"},
  {"source": "def_concatenation", "target": "pro_jordan-curve-orientation", "type": "dashed"},
  {"source": "def_concatenation", "target": "thm_gerver-monotone", "type": "dashed"},
  {"source": "def_concatenation", "target": "lem_convex-curve-concat", "type": "dashed"},
  {"source": "def_concatenation", "target": "pro_curve-area-functional-additive", "type": "dashed"},
  {"source": "thm_curve-area-functional-area", "target": "thm_convex-curve-area-functional", "type": "solid"},
  {"source": "thm_curve-area-functional-area", "target": "lem_cap-left-right-tail", "type": "solid"},
  {"source": "thm_curve-area-functional-area", "target": "lem_cap-middle-lower-estimate", "type": "solid"},
  {"source": "lem_convex-curve-concat", "target": "lem_upper-boundary-tracing", "type": "solid"},
  {"source": "pro_curve-area-functional-additive", "target": "lem_cap-left-right-tail", "type": "solid"},
  {"source": "def_curve-area-functional", "target": "thm_mamikon", "type": "solid"},
  {"source": "def_curve-area-functional", "target": "thm_variation-curve", "type": "dashed"},
  {"source": "def_curve-area-functional", "target": "thm_variation-segment", "type": "dashed"},
  {"source": "def_curve-area-functional", "target": "pro_curve-area-functional-additive", "type": "solid"},
  {"source": "def_curve-area-functional", "target": "pro_curve-area-line-segment", "type": "dashed"},
  {"source": "pro_curve-area-line-segment", "target": "thm_convex-curve-area-functional", "type": "solid"},
  {"source": "pro_curve-area-line-segment", "target": "pro_curve-area-line-segment-colinear", "type": "solid"},
  {"source": "pro_curve-area-functional-quadratic", "target": "pro_upper-bound-q-quadratic", "type": "solid"},
  {"source": "def_upper-bound-q", "target": "thm_variation-a2", "type": "solid"},
  {"source": "def_upper-bound-q", "target": "thm_upper-bound-q-gerver-match", "type": "solid"},
  {"source": "def_upper-bound-q", "target": "lem_upper-bound-decomposition", "type": "solid"},
  {"source": "def_mamikon-middle", "target": "lem_mamikon-middle-eq", "type": "solid"},
  {"source": "def_upper-bound-middle", "target": "lem_upper-bound-decomposition", "type": "solid"},
  {"source": "lem_linvals", "target": "lem_mamikon-middle-eq", "type": "solid"},
  {"source": "def_gerver-intervals", "target": "def_interval-j", "type": "dashed"},
  {"source": "def_interval-j", "target": "thm_variation-a2-gerver", "type": "solid"},
  {"source": "def_gerver-x", "target": "def_gerver-abcd", "type": "dashed"},
  {"source": "thm_gerver-odes", "target": "thm_upper-bound-q-gerver", "type": "solid"},
];
